version: "3.9"

services:
  juridical-selenium:
    container_name: juridical-selenium
    image: selenium/standalone-chrome:4.1.1-20220121
    ports:
      - "4444:4444"
    expose:
      - 4444
    networks:
      - worker-network
    restart: always
  
  juridical-worker:
    container_name: juridical-worker
    image: juridical-worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Production
      - LEGAL_PROCESS_USER
      - LEGAL_PROCESS_PASSWORD
      - MESSAGE_SERVICE_API_TOKEN
      - MESSAGE_SERVICE_TO
      - MESSAGE_SERVICE_FROM
      - Logging__Console__FormatterName=""
    networks:
      - worker-network
    depends_on:
      - juridical-selenium
    restart: always

networks:
  worker-network:
    name: worker-network
    driver: bridge
