version: "3.9"

services:
  juridical-selenium:
    container_name: juridical-selenium
    hostname: juridical-selenium
    image: selenium/standalone-chrome:110.0
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    expose:
      - 4444
    networks:
      - worker-network
    restart: always
  
  juridical-legal-process-worker:
    container_name: juridical-legal-process-worker
    image: juridical-legal-process-worker
    build:
      context: ./src
      dockerfile: Juridical.LegalProcess.Worker/Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - worker-network
    depends_on:
      - juridical-selenium
    restart: always

  juridical-message-worker:
    container_name: juridical-message-worker
    image: juridical-message-worker
    build:
      context: ./src
      dockerfile: Juridical.Message.Worker/Dockerfile
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Development
    networks:
      - worker-network
    restart: always

networks:
  worker-network:
    name: worker-network
    driver: bridge
