apiVersion: apps/v1
kind: Deployment

metadata:
  name: juridical-selenium
  namespace: juridical
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juridical-selenium
    spec:
      containers:
        - name: juridical-selenium
          image: selenium/standalone-chrome:123.0
          ports:
            - containerPort: 4444
          env:
            - name: JAVA_OPTS
              value: '-Dwebdriver.chrome.whitelistedIps=""'
      restartPolicy: Always
  selector:
    matchLabels:
      app: juridical-selenium
