apiVersion: apps/v1
kind: Deployment

metadata:
  name: juridical-legal-process-worker
  namespace: juridical
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juridical-legal-process-worker
    spec:
      containers:
        - name: juridical-legal-process-worker
          image: us-east1-docker.pkg.dev/LEGAL_PROCESS_IMAGE:TAG
          envFrom:
            - configMapRef:
                name: juridical-legal-process-config-map
            - secretRef:
                name: juridical-legal-process-secret
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 25
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 25
            failureThreshold: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: juridical-legal-process-worker
