apiVersion: apps/v1
kind: Deployment

metadata:
  name: juridical-worker
  namespace: juridical
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juridical-worker
    spec:
      containers:
        - name: juridical-worker
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: Logging__Console__FormatterName
              value: ""
          envFrom:
            - secretRef:
                name: juridical-worker-secret
      restartPolicy: Always
  selector:
    matchLabels:
      app: juridical-worker
