apiVersion: apps/v1
kind: Deployment

metadata:
  name: juridical-message-worker
  namespace: juridical
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: juridical-message-worker
    spec:
      containers:
        - name: juridical-message-worker
          image: gcr.io/PROJECT_ID/MESSAGE_IMAGE:TAG
          envFrom:
            - configMapRef:
                name: juridical-message-config-map
            - secretRef:
                name: juridical-message-secret
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 25
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 25
            failureThreshold: 3
      restartPolicy: Always
  selector:
    matchLabels:
      app: juridical-message-worker
