name: juridical-worker-deploy

on:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "**/README.md"
    branches:
      - main

  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCR_IMAGE: juridical-worker

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Docker configuration
        run: |-
          gcloud --quiet auth configure-docker

      - name: Docker build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$GCR_IMAGE:$GITHUB_SHA" \
            --tag "gcr.io/$PROJECT_ID/$GCR_IMAGE:latest" \
            .

      - name: Docker publish
        run: |-
          docker push --all-tags "gcr.io/$PROJECT_ID/$GCR_IMAGE"
